languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Trevor Saudi"
logo = "img/logo.jpg"
description = "Portfolio/blog"
copyright = ":smile: "

dateFormat = "2 January 2006"

[author]
name = "Trevor Saudi"
image = "img/profile.jpg"
headline = "Information Security Consultant"
bio = "A little bit abousdfsdfsdft you"
links = [
  { github = "https://github.com/trevorsaudi" } 
   ]
